server:
  port: 8081
  tomcat:
    max-threads: 200
    uri-encoding: "UTF-8"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: l914119972
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      suffix: .html
      prefix: /
mybatis:
  type-aliases-package: com.lhh.demo.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
WXLoginRequestUrl: https://api.weixin.qq.com/sns/jscode2session
WXAppId: wxb491ee5a3dde60d8
WXAppSecret: abc0e54e183e56cacb06d41c33045b64